### ISSUE TITLE
Error running ddm.plot.model_gui()

### ISSUE THREAD

**Issue by acburns** [mwshinn/PyDDM#11]
Hi Max, 

Thanks for the very cool looking package! 

I am running through the roitman_shadlen.py tutorial now and am running into an error when I run this function: 

Line 104: ddm.plot.model_gui(model=fit_model_rs, sample=roitman_sample)

------
Returns this error:

ddm.plot.model_gui(model=fit_model_rs, sample=roitman_sample)
cond var vals [{'0.0': 0.0, '0.032': 0.032000000000000001, '0.064': 0.064000000000000001, '0.128': 0.128, '0.256': 0.25600000000000001, '0.512': 0.51200000000000001}]
cond vars [<tkinter.StringVar object at 0x000002715063D2B0>]
D:\Anaconda3\lib\site-packages\matplotlib\figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
Traceback (most recent call last):

  File "<ipython-input-27-36423aec766d>", line 1, in <module>
    ddm.plot.model_gui(model=fit_model_rs, sample=roitman_sample)

  File "D:\Anaconda3\lib\site-packages\ddm\plot.py", line 501, in model_gui
    set_defaults()

  File "D:\Anaconda3\lib\site-packages\ddm\plot.py", line 489, in set_defaults
    update()

  File "D:\Anaconda3\lib\site-packages\ddm\plot.py", line 402, in update
    plot(model=m, fig=fig, sample=sample, conditions=current_conditions, data_dt=data_dt)

  File "D:\Anaconda3\lib\site-packages\ddm\plot.py", line 232, in plot_fit_diagnostics
    fig.tight_layout()

  File "D:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1752, in tight_layout
    rect=rect)

  File "D:\Anaconda3\lib\site-packages\matplotlib\tight_layout.py", line 322, in get_tight_layout_figure
    max_nrows = max(nrows_list)

ValueError: max() arg is an empty sequence

-----

Initially it was producing a GUI with an error message but this no longer happens. 

Kind regards,

Angus

**Comment by mwshinn** [comment]
Hi Angus,

Thank you for your bug report!  Could you please let me know what version of Python, PyDDM, and matplotlib you are running as well as the OS?  This can all be determined with the following python script:

```
import platform, matplotlib, ddm, sys
print(sys.version)
print(platform.platform())
print(matplotlib.__version__)
print(ddm.__version__)
```

Also, are you using a Jupyter notebook?

**Comment by mwshinn** [comment]
Also, are you using PyCharm?

**Comment by acburns** [comment]
Hi Max,

Your above code returns the following:
---
print(sys.version)
3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]

print(platform.platform())
Windows-10-10.0.18362-SP0

print(matplotlib.__version__)
2.0.0

print(ddm.__version__)
0.3.0
---

Here is an image of the error message in the GUI:
![pyddm_gui_error](https://user-images.githubusercontent.com/26035086/68628691-80c4ad00-0535-11ea-843e-ec62d62bd8a9.JPG)

I'm not using PyCharm or a Jupyter Notebook, just running this in Spyder. 

---

Also, as an aside - I might be missing this in the docs but how can I print the model fit (i.e. BIC) for a given model/data set? This would be useful for model comparison. 

Regards,

Angus

**Comment by mwshinn** [comment]
Hi Angus,

It seems that the problem was due to a bug in an old version of matplotlib.  I updated PyDDM to be compatible with version 2.0.  You can download and install from github, but an update isn't ready for a release to pip yet.  You could alternatively update matplotlib to solve the problem. Let me know whether or not this fixes the problem for you!

**Comment by mwshinn** [comment]
Regarding access to the model fit, thanks for pointing out the lack of documentation.  The short answer is that you can use Model.fitresult after performing the fit.  The long answer will be on its way - I opened #12 to address this.

**Comment by acburns** [comment]
Hi Max,

Thanks very much for these helpful responses and a great package. 

Regards,
Angus
