### ISSUE TITLE
IndexError when interating over Sample.items() 

### ISSUE THREAD

**Issue by cherepaha** [mwshinn/PyDDM#14]
First, thanks for putting together this great package! 

Second, I'm not sure if that's a bug or I'm doing something wrong, but I'm getting `IndexError` when iterating over `Sample.items()`. 

This code
```python
import pandas as pd
import ddm
import paranoid as pns
pns.settings.Settings.set(enabled=False)

exp_data = pd.read_csv('measures.csv', usecols=['subj_id', 'RT', 'is_turn_decision'])
exp_sample = ddm.Sample.from_pandas_dataframe(df=exp_data, rt_column_name='RT', correct_column_name='is_turn_decision')
rts = [item[0] for item in exp_sample.items(correct=True)]
```
results in 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-28-b68ea2d791d2> in <module>
----> 1 rts = [item[0] for item in exp_sample.items(correct=True)]

<ipython-input-28-b68ea2d791d2> in <listcomp>(.0)
----> 1 rts = [item[0] for item in exp_sample.items(correct=True)]

C:\ProgramData\Anaconda3\lib\site-packages\ddm\sample.py in __next__(self)
    396             rt = self.sample.err
    397             ind = 1
--> 398         return (rt[self.i-1], {k : self.sample.conditions[k][ind][self.i-1] for k in self.sample.conditions.keys()})
    399 

IndexError: index 350 is out of bounds for axis 0 with size 350
```

where 350 is the length of my correct RTs, and the data is [measures.csv](https://github.com/cherepaha/evidence_accumulation_in_gap_acceptance/blob/master/data/measures.csv).

Taking a quick look at `_Sample_Iter_Wraper.__next__()`, it seems like the iterator would only stop at `len(self.sample)`:
```python
if self.i == len(self.sample):
    raise StopIteration
```
whereas I'd guess it should stop earlier, at `len(self.sample.corr)` or `len(self.sample.err)`. If not, I am confused and would appreciate a quick hint on how to iterate over correct/error RTs...

Also, if I don't disable paranoid warnings, I cannot even create a sample from dataframe:
```
EntryConditionsError: Invalid function requirement 'not np.any(np.isnan(df))' in Sample.from_pandas_dataframe
```
 but that's probably another issue...

**Comment by mwshinn** [comment]
Thanks for your bug report!  I fixed both of these issues (the Paranoid issue and the iteration issue) but if you just want to get the list of RTs in a sample without the accompanying information, you can use sample.corr and sample.err.  I updated the documentation of the items() function to clarify this.
