### ISSUE TITLE
exception when bound collapses to 0

### ISSUE THREAD

**Issue by ntardiff** [mwshinn/PyDDM#17]
When using collapsing bound models, exceptions can occur when the bound collapses to 0. I first observed this behavior in a hyperbolic collapsing bound model I was trying to fit, which would raise the following exception: 

> File "/home/ntardiff/data/miniconda2/envs/py36/lib/python3.6/site-packages/pyddm-0.3.0-py3.6.egg/ddm/model.py", line 662, in solve_numerical_implicit
>   File "/home/ntardiff/data/miniconda2/envs/py36/lib/python3.6/site-packages/paranoid/decorators.py", line 114, in _decorated
>     return func(*args, **kwargs)
>   File "/home/ntardiff/data/miniconda2/envs/py36/lib/python3.6/site-packages/pyddm-0.3.0-py3.6.egg/ddm/model.py", line 576, in solve_numerical
>   File "/home/ntardiff/data/miniconda2/envs/py36/lib/python3.6/site-packages/paranoid/decorators.py", line 114, in _decorated
>     return func(*args, **kwargs)
>   File "/home/ntardiff/data/miniconda2/envs/py36/lib/python3.6/site-packages/pyddm-0.3.0-py3.6.egg/ddm/tridiag.py", line 135, in spsolve
> ValueError: unexpected array size: new_size=1, got array with arr_size=0

When trying to solve a model rather than fitting, the exception raised is:

>    s4 = model4.solve()
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 126, in _decorated
>     returnvalue = func(*args, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\model.py", line 420, in solve
>     return self.solve_numerical_implicit(conditions=conditions, return_evolution=return_evolution)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 126, in _decorated
>     returnvalue = func(*args, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\model.py", line 662, in solve_numerical_implicit
>     return self.solve_numerical(method="implicit", conditions=conditions, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 126, in _decorated
>     returnvalue = func(*args, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\model.py", line 576, in solve_numerical
>     pdf_inner = diffusion_matrix.splice(1,-1).spsolve(pdf_prev[x_index_inner:len(x_list)-x_index_inner])
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\tridiag.py", line 94, in splice
>     return TriDiagMatrix(diag=self.diag[lower:upper], up=self.up[lower:upper-1], down=self.down[lower:upper-1])
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 125, in _decorated
>     _check_requires(func, argvals)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 49, in _check_requires
>     raise E.EntryConditionsError("Function requirement '%s' failed in %s\nparams: %s" % (requirementtext,  func.__qualname__, str(argvals)))
> EntryConditionsError: Function requirement 'len(up) > 0' failed in TriDiagMatrix.__init__
> params: {'self': <ddm.tridiag.TriDiagMatrix object at 0x0000026F36DFC6D8>, 'diag': array([10001.]), 'up': array([], dtype=float64), 'down': array([], dtype=float64)}

I also confirmed this same error can occur with BoundCollapsingStep when solving, though I had no issues when fitting using BoundCollapsingExponential and also didn't reproduce when trying to solve BoundCollapsingLinear, though I only made a cursory attempt on that one.

It appears that the problem is averted as long as the bound is >= dx. E.g., with dx=.001, allowing the bound to collapse to .0009 fails, but .001 is OK [i.e returning max(boundfunc, .001) from get_bound()].

**Comment by mwshinn** [comment]
Thanks for your bug report!  Should be good now!
