### ISSUE TITLE
error in Sample.subset()

### ISSUE THREAD

**Issue by ntardiff** [mwshinn/PyDDM#18]
Hi again,

Sorry to be bugging you again so soon. I just upgraded to the most recent version from github and now am encountering the following error:

>     model_fit = fit_adjust_model(sample=sample, model=model)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\functions.py", line 310, in fit_adjust_model
>     nparams=len(params), samplesize=len(sample))
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\models\loss.py", line 56, in __init__
>     self.setup(**kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\models\loss.py", line 153, in setup
>     for comb in self.sample.condition_combinations(required_conditions=self.required_conditions):
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 114, in _decorated
>     return func(*args, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\sample.py", line 320, in condition_combinations
>     if len(self.subset(**dict(zip(names, p)))) != 0:
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\paranoid\decorators.py", line 114, in _decorated
>     return func(*args, **kwargs)
>   File "C:\Users\ntard\miniconda3\envs\py36\lib\site-packages\pyddm-0.3.0-py3.6.egg\ddm\sample.py", line 269, in subset
>     v[2][mask_undec] if len(v) == 3 else np.asarray([])
> 
> TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by mwshinn** [comment]
What is the exact version you are on? (i.e. the output of "git rev-parse HEAD"?)  This was a bug from a few days ago but I thought it was fixed.

**Comment by ntardiff** [comment]
It's c8671a558ff1fbca54542a031b075543aa893727

**Comment by mwshinn** [comment]
Thanks for the bug report.  The latest commit should fix it!  Let me know if it's still not working for you.

**Comment by ntardiff** [comment]
All good. Thanks!
