### ISSUE TITLE
Noise in documentation

### ISSUE THREAD

**Issue by jCalderTravis** [mwshinn/PyDDM#19]
Thank you for you an amazing piece of software for DDM models.

Should the get_noise method of the Noise class return the standard deviation or the variance of the noise? In places in the documentation it sounds like it should return the variance, but in the methods section of your preprint it sounds like the standard deviation.

Thanks for any clarification, and for your time.

**Comment by mwshinn** [comment]
Thank you for pointing this out!  The documentation has been updated to clarify that it is standard deviation, not variance.
