### ISSUE TITLE
renormalization warnings

### ISSUE THREAD

**Issue by ntardiff** [mwshinn/PyDDM#23]
Following up on the previous discussion from #21:

> Regarding the second issue with lots of renormalization warnings in the analytic solver, this seems a bit more serious. Could you please describe these in more detail in a bug report? I will close this PR, so if you could open a new bug report that would be best instead of reusing this thread.

After digging a little more, I don't think this is specifically about the analytic solver. I found one instance in which the numeric solver also gave frequent renormalization warnings during fitting, and this was a case in which I had made the initial bound height of an exponentially collapsing bound was a linear function of a parametric condition.  A number of very similar models without this feature did not raise any warnings.

When I switched to the analytic solver, I switched from an exponentially-collapsing bound to a linearly-collapsing bound, and it seems that the linearly collapsing bound frequently produces these warnings.

So I am wondering if the issue is less about the solver and more about extreme conditions that become possible with certain types of bounds but not others? Sorry I don't have more insight than this at the moment...

**Comment by mwshinn** [comment]
Thanks for following up on the bug report.  Could you please give a short bit of example code which causes the frequent renormalization warnings you are describing?

**Comment by ntardiff** [comment]
Apologies for the delay. The models where I've been getting the warnings are pretty complex, so I was trying to see if I could get them in simpler cases. One case I've identified is for certain combinations of very low bound height and very high drift. So for example fitting this model on some of my data, with these extreme minvals/maxvals to provoke the warning:

```
mtest = Model(name='mtest',
             drift=DriftCoherence(driftcoh=Fittable(minval=10, maxval=40)),
             bound=BoundConstant(B=Fittable(minval=.1, maxval=.2)),
             dx=.005, dt=.005, T_dur=2.0)
```

I can also confirm that similar ranges will give a warning when input directly into solve_analytical, e.g.,

```
    T_dur=2.00
    dt=.002
    drift=19
    noise=1
    b=0.1
    teval=np.arange(0., T_dur+0.1*dt, dt)
    b_slope=0
    
    pdf_c1,pdf_e1=solve_analytical(drift, noise, b, teval, b_slope,dt)
    
```

Strangely, I tried to replicate this using the Roitman & Shadlen data and roitman_shadlen.py script and I don't get warnings, so I'm not sure what is happening there and whether there a certain conditions in which that output is suppressed.

Like I said, the fits where I've been getting the warnings involve fairly complicated models w/ a number of free parameters in the drift rate (that I've allowed fairly wide minval/maxval ranges for) and collapsing bounds, so perhaps it is just more likely that this extreme part of the parameter space (or others that could also give this warning) get explored in this case compared to simpler models? As far as I can tell it's not causing any issues, as my fits seem pretty reasonable.

**Comment by mwshinn** [comment]
I was able to run through the test case you described for the analytical solver.  When I decrease dt like the warning message suggests, the warning goes away.  It seems like the places where you are getting the renormalization warnings are indeed places where the numerical parameters are not able to give high accuracy. This is the reason that these warnings exist: to warn users when the numerical parameters are insufficient for the model.  Usually they occur for extreme parameter ranges, e.g. large drift or noise, short bounds, etc.  So this is a limitation of the numerical methods, not a bug in PyDDM.

Is there a different behavior you would expect PyDDM to do here?

**Comment by ntardiff** [comment]
Understood. I think I was just initially surprised b/c I wasn't getting
these warnings w/ the numerical solver, but subsequent experience suggests
to me that the analytical solver is more sensitive to the time resolution
at extreme values and perhaps that's why it happens more in the analytical
solver.

I don't think I would necessarily expect a different behavior, but perhaps
including an additional suggestion to further restrict minval/maxval of
your parameters when fitting would be helpful to users?
