### ISSUE TITLE
set disp=False or disp=verbose when using `differential_evolution` method

### ISSUE THREAD

**Issue by morteza** [mwshinn/PyDDM#27]
First, thanks a lot for this awesome package! 🏆 

I'm trying to use it in a Jupyter notebook, but the textual outputs make it hard to quickly diagnose the final results and plots.

I tried `verbose=False` but scipy still produces some outputs at every fitting step. I think the reason is `scipy.optimize.differential_evolution` uses `disp` param to print out evaluations at every step, and this `disp` is hardcoded and cannot be overridden by `verbose` or passing custom `fitparams`:

https://github.com/mwshinn/PyDDM/blob/9f107abfb307924c2dbd2c8b104e5267671e2bd4/ddm/functions.py#L345

Since `disp` is already used in that function call, it cannot be overridden by `fitparams` and the following code raises an error:

```
model_fit = fit_adjust_model(sample=_SAMPLE, model=model, verbose=False, fitparams={'disp':False})
```

The text it prints is like this:

```
differential_evolution step 1: f(x)= -63.8486
differential_evolution step 2: f(x)= -91.0174
differential_evolution step 3: f(x)= -150.359
differential_evolution step 4: f(x)= -152.205
differential_evolution step 5: f(x)= -212.682
differential_evolution step 6: f(x)= -212.682
differential_evolution step 7: f(x)= -221.318
...
```

It only occurs when differential_evolution is used as the fitting method.

Quick solution would be removing that hardcoded `disp` or setting it equal to `verbose`.

**Comment by mwshinn** [comment]
Hi Morteza,

Thanks for your clear and well-thought-out bug report.  This made it very easy to fix the bug you describe.  Everything should work as intended in the latest commit.
