### ISSUE TITLE
ICGaussian - possibly wrong symmetric x verification

### ISSUE THREAD

**Issue by odedwer** [mwshinn/PyDDM#33]
In ic.py line 170, there is a `@requires("np.all(np.isclose(x-x[::-1], 0))") # Symmetric across x=y`. As x is symmetric over 0, it produces an error when attempting to use ICGaussian for IC parameter in model initialization. It is possible to fix this by changing the verification to `@requires("np.all(np.isclose(x+x[::-1], 0))") # Symmetric across x=y`.
We use the following code that produces the error:
`import ddm
m = ddm.Model(name='Simple model', IC=ddm.ICGaussian(stdev=0.3),
              drift=ddm.DriftConstant(drift=2.2),
              noise=ddm.NoiseConstant(noise=1.5),
              bound=ddm.BoundConstant(B=1.1),
              overlay=ddm.OverlayNonDecision(nondectime=.1),
              dx=.001, dt=.01, T_dur=2)
sol: ddm.Solution = m.solve()`

**Comment by mwshinn** [comment]
Thanks for the bug report!  The new commit should fix it.  It also includes extra test cases to make sure something like this doesn't slip through the cracks again.
