### ISSUE TITLE
minor typo in docs/faq?

### ISSUE THREAD

**Issue by hauselin** [mwshinn/PyDDM#41]
In [this section](https://pyddm.readthedocs.io/en/stable/faqs.html#what-arguments-do-get-drift-get-noise-etc-take) of the FAQ, `class BoundReward(ddm.Drift)` should be `class BoundReward(ddm.Bound)` in the example code chunks?

**Comment by mwshinn** [comment]
Yes, that's right, thanks for catching that!  Just fixed it.
