### ISSUE TITLE
Warning for distribution sum

### ISSUE THREAD

**Issue by lehcni** [mwshinn/PyDDM#43]
Hi, 
I frequently get "Warning, distribution sums to 1.000000 rather than 1" from the following line:
https://github.com/mwshinn/PyDDM/blob/d5d7747cce212c0ebe550324bf33f8625a24e2fd/ddm/solution.py#L321

**Comment by mwshinn** [comment]
We deal with this a bit more elegantly now, as we do in other parts of the code.  Should be fixed in the mainline!
