### ISSUE TITLE
Error when using different fitting algorithms

### ISSUE THREAD

**Issue by saeedeh** [mwshinn/PyDDM#45]
I'm running the example on monkey data [here](https://colab.research.google.com/github/mwshinn/PyDDM/blob/master/doc/notebooks/pyddm_gddm_short_tutorial.ipynb#scrollTo=BTOU4e_ljHAG).

If we change the fitting method from default to 'simple', 'simplex', or 'basin' like this:

`fit_model_rs = fit_adjust_model(sample=roitman_sample, model=model_rs, verbose=False, method='simple')`

It gives the following error:

`RuntimeError: The map-like callable must be of the form f(func, iterable), returning a sequence of numbers the same length as 'iterable'`

**Comment by mwshinn** [comment]
Thank you for your bug report.  What version of Python and Scipy are you running?  (You can get this from "import platform,scipy; print(platform.python_version()); print(scipy.__version__)".)  Also, could you please provide the exact change you are making in google colab?  I can't seem to reproduce the problem.

**Comment by saeedeh** [comment]
Thanks for your reply. In the colab, I am changing this line:
`fit_model_rs = fit_adjust_model(sample=roitman_sample, model=model_rs, verbose=False)`
to
`fit_model_rs = fit_adjust_model(sample=roitman_sample, model=model_rs, verbose=False, method='simple')`

But I just realized the solution. In the tutorial [here](https://pyddm.readthedocs.io/en/stable/cookbook/howto.html?highlight=basin#fitting-models-with-custom-algorithms) it says we can change fitting algorithm to "simple", "simplex" or "basin" with the _method_ argument, but it is actually _fitting_method_ argument. So this works:
`fit_model_rs = fit_adjust_model(sample=roitman_sample, model=model_rs, verbose=False, fitting_method='simple')`

**Comment by mwshinn** [comment]
Great, glad it is resolved!  Was there a place in the documentation where it said to use the "method" argument instead of the "fitting_method" argument?  Just want to correct it if so.

**Comment by saeedeh** [comment]
Yes, here: https://pyddm.readthedocs.io/en/stable/cookbook/howto.html?highlight=basin#fitting-models-with-custom-algorithms
Thanks!

**Comment by mwshinn** [comment]
Thanks!  Here is the updated page: https://pyddm.readthedocs.io/en/latest/cookbook/howto.html?highlight=basin#fitting-models-with-custom-algorithms
