### ISSUE TITLE
Seed option in evolution strategy for reporting stability.

### ISSUE THREAD

**Issue by nightvision04** [mwshinn/PyDDM#61]
In functions.py line 403, `random.normal()` and `random.random()` are called during the evolution_strategy.

I am using pyDDM for a paper and am wrestling with a few unstable parameters. I would really help out if these two steps could be optionally seeded for solution stability. Would you be comfortable if I proposed a PR for this?

**Comment by mwshinn** [comment]
Yes, absolutely!  Currently, evolution_strategy doesn't get used very often compared to the others so any improvements would be great.  I recall it had some convergence issues and I was considering removing it at one point - it was initially implemented for a feature of the GUI which I never ended up finishing.  You also might want to try the simplex method, which has many of the same advantages of local search but is a lot faster.  Gradient descent ("simple") is also good for local refinement depending on how jagged your optimization landscape is.
