### ISSUE TITLE
Sample.__eq__ errors

### ISSUE THREAD

**Issue by covertg** [mwshinn/PyDDM#68]
I recently discovered that equality comparison of two Samples via `==` could raise a ValueError when the Samples are of different sizes (in particular, if the `sample_corr`s and/or `sample_err`s are of a different size). E.g.:
```python
import numpy as np
import pyddm
s1 = pyddm.Sample(sample_corr=np.array([0, 1]), sample_err=np.array([]))
s2 = pyddm.Sample(sample_corr=np.array([0, 1, 2]), sample_err=np.array([]))
s1 == s2
```
```python
ValueError: operands could not be broadcast together with shapes (2,) (3,) `
```
This appears to be due to `Sample.__eq__`'s use of `np.allclose()` on the input arrays. If the arrays can be broadcast together, no error is raised; otherwise we get a ValueError.

Thinking more on this also made me wonder: is the equality operator for Samples invariant to array order? Currently it is not; i.e. we have:
```python
s3 = pyddm.Sample(sample_corr=np.array([0, 1]), sample_err=np.array([]))
s4 = pyddm.Sample(sample_corr=np.array([1, 0]), sample_err=np.array([]))
s3 == s4
```
```python
False
```
My prior assumption was that it should be, although perhaps I could be mistaken.

**Comment by mwshinn** [comment]
This was an interesting case where there was a test case for it but the test case had a bug which masked the bug in the code.  And you are correct, if the sort order is different, we call them different samples.  It is really hard to do sort orders in the correct way and there aren't very many use cases for this.
