### ISSUE TITLE
Manual implementation of clasic Ornstein Uhlenbeck process not working

### ISSUE THREAD

**Issue by jaygastby1991** [mwshinn/PyDDM#72]
I just tried to implement  the classic Ornstein Uhlenbeck process, creating a custom Drift class:
![image](https://user-images.githubusercontent.com/109085475/214951486-19961648-8565-4922-bd7a-93bf43d960a0.png)
![image](https://user-images.githubusercontent.com/109085475/214951867-e38b528f-4860-4082-b5cb-0521f1bd2fdc.png)
However, when attempting to solve the model, the following appears:
![image](https://user-images.githubusercontent.com/109085475/214952378-76a32704-da91-4811-85f6-54959af557fd.png)

**Comment by mwshinn** [comment]
You need to switch the order of "self" and "x" in the get_drift function and then it should work.  "self" should always be the first argument in python methods, e.g., see [this tutorial](https://www.w3schools.com/python/gloss_python_self.asp).
