### ISSUE TITLE
model.solve() error for model variant with DriftCoherence

### ISSUE THREAD

**Issue by lianaan** [mwshinn/PyDDM#73]
Hi Max and colleagues: 
Thank you so much for this package! I was able to fit a few model variants, all in which drift varies linearly with coherence (class DriftCoherence), and also with either Starting point (ICPointSideBiasRatio) and/or drift bias (DriftCoherenceRewBias). Getting the outputs, log likelihood and parameter estimates has been great! I would also like to generate plots of model predictions, the psychometric and chronometric fits.  However, when trying to get the model predictions with sol = model.solve(), while the sample provided works for me also (simple.py from your quickstart link https://pyddm.readthedocs.io/en/stable/quickstart.html), when I replaced the model.txt file with my own output files (for instance Mae_s_1_c_1.csv._base_model_output.txt), I get the error below. Any help would be appreciated, I have very little experience in Python. 

runfile('/Users/horgalab/Documents/Python/simpleE.py', wdir='/Users/horgalab/Documents/Python')
Traceback (most recent call last):

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/Python/simpleE.py:75
    sol = model_loaded.solve(conditions=cond_all)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paranoid/decorators.py:114 in _decorated
    return func(*args, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyddm/model.py:512 in solve
    return self.solve_analytical(conditions=conditions)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paranoid/decorators.py:114 in _decorated
    return func(*args, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyddm/model.py:552 in solve_analytical
    anal_pdf_corr, anal_pdf_err = analytic_ddm(self.get_dependence("drift").get_drift(t=0, x=0, conditions=conditions),

  File ~/Documents/Python/simpleE.py:32 in get_drift
    return self.driftcoh * conditions['coh']

TypeError: can't multiply sequence by non-int of type 'Fitted'

 File /Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/Python/simpleE_ours.py:81
    sol = model_loaded.solve_numerical_implicit(conditions=conditions)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paranoid/decorators.py:114 in _decorated
    return func(*args, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyddm/model.py:861 in solve_numerical_implicit
    return self.solve_numerical(method="implicit", conditions=conditions, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paranoid/decorators.py:114 in _decorated
    return func(*args, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyddm/model.py:744 in solve_numerical
    drift_matrix = self.get_dependence('drift').get_matrix(x=x_list_inbounds, t=t, dt=self.dt, dx=self.dx, conditions=conditions)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/paranoid/decorators.py:114 in _decorated
    return func(*args, **kwargs)

  File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyddm/models/drift.py:46 in get_matrix
    drift = self.get_drift(x=x, t=t, dx=dx, dt=dt, conditions=conditions, **kwargs)

  File ~/Documents/Python/simpleE_ours.py:26 in get_drift
    return float(self.driftcoh) * conditions['coh']

TypeError: can't multiply sequence by non-int of type 'float'

Please find below our script simpleE.py:

`# Simple demonstration of PyDDM.
from pyddm import Sample
import pandas
# Create a simple model with constant drift, noise, and bounds.
from pyddm import Model
from pyddm.models import DriftConstant, NoiseConstant, BoundConstant, OverlayNonDecision, OverlayChain, ICPointSourceCenter, OverlayPoissonMixture, LossRobustLikelihood
from pyddm.functions import fit_adjust_model, display_model
import pyddm as ddm

# Solve the model, i.e. simulate the differential equations to
# generate a probability distribution solution.
#display_model(model)
#sol = model.solve()

# Now, sample from the model solution to create a new generated
# sample.
#samp = sol.resample(1000)

# Fit a model identical to the one described above on the newly
# generated data so show that parameters can be recovered.
from pyddm import Fittable, Fitted
from pyddm.models import LossRobustBIC
from pyddm.functions import fit_adjust_model

class DriftCoherence(ddm.models.Drift):
    name = "Drift depends linearly on coherence"
    required_parameters = ["driftcoh"] # <-- Parameters we want to include in the model
    required_conditions = ["coh"] # <-- Task parameters ("conditions"). Should be the same name as in the sample.
    
    # We must always define the get_drift function, which is used to compute the instantaneous value of drift.
    def get_drift(self, conditions, **kwargs):
        return self.driftcoh * conditions['coh']

model_base = Model(name='Roitman data, drift varies with coherence',
                 drift=DriftCoherence(driftcoh=Fittable(minval=0, maxval=20)),
                 noise=NoiseConstant(noise=1),
                 bound=BoundConstant(B=Fittable(minval=.1, maxval=3)),
                 overlay=OverlayChain(overlays=[OverlayNonDecision(nondectime=Fittable(minval=0, maxval=2)),
                                                OverlayPoissonMixture(pmixturecoef=.02,
                                                                      rate=1)]),
              dx=.01, dt=.0005, T_dur=2.999)

with open("roitman_rts.csv", "r") as f:
    df_rt = pandas.read_csv(f)

#df_rt = df_rt[df_rt["monkey"] == 1] # Only monkey 1
  
# Remove short and long RTs, as in 10.1523/JNEUROSCI.4684-04.2005.
# This is not strictly necessary, but is performed here for
# compatibility with this study.
df_rt = df_rt[df_rt["rt"] > .1] # Remove trials less than 100ms
df_rt = df_rt[df_rt["rt"] < 1.65] # Remove trials greater than 1650ms
  
# Create a sample object from our data.  This is the standard input
# format for fitting procedures.  Since RT and correct/error are
# both mandatory columns, their names are specified by command line
# arguments.
roitman_sample = Sample.from_pandas_dataframe(df_rt, rt_column_name="rt", correct_column_name="correct")

cond_all={"coh": [0.0, 0.005, 0.010, 0.015, 0.020, 0.025, 0.030, 0.035, 0.040, 0.045, 0.050,0.055, 0.060,0.065,0.070, \
 0.075,0.080, 0.085, 0.090, 0.095, 0.100, 0.105, 0.110, 0.115, 0.120, 0.125, 0.130, 0.135, 0.140, \
 0.145, 0.150, 0.155, 0.160, 0.165, 0.170, 0.175,0.180, 0.185, 0.190, 0.195,0.200, 0.205, 0.210, \
 0.215, 0.220, 0.225, 0.230, 0.235, 0.240, 0.245, 0.250, 0.255, 0.260, 0.265, 0.270, 0.275, 0.280, \
 0.285, 0.290, 0.295, 0.300],"left_is_correct": [0,1]}

# Load the model
from pyddm import FitResult
with open("mae_s_1_c_1.csv_base_model_output.txt", "r") as f:
    model_loaded = eval(f.read())
#with open("model.txt", "r") as f:
#    model_loaded = eval(f.read())
    
#sol = model_loaded.solve()  
sol = model_loaded.solve(conditions=cond_all) 

print(sol.prob_correct())
print(sol.pdf_err())

# Plot the model fit to the PDFs and save the file.
import pyddm.plot
import matplotlib.pyplot as plt
pyddm.plot.plot_fit_diagnostics(model=model_loaded, sample=roitman_sample)
plt.savefig("simple-fit.png")
plt.show()`

[mae_s_1_c_1.csv_base_model_output.txt](https://github.com/mwshinn/PyDDM/files/10886849/mae_s_1_c_1.csv_base_model_output.txt)

**Comment by mwshinn** [comment]
Hi Andra,

It looks like your conditions are in the wrong format.  When you call model.solve(), the "conditions" argument should be one condition per dictionary key, not a list.  I assume you intend with this to solve it for all of the conditions in the list that you passed.  But actually, you are assigning the condition value to a list.  This is probably not what you want, since a solution generally should have one specific drift value.  If you do want to solve for multiple coherences, then use [solve_partial_conditions](https://pyddm.readthedocs.io/en/stable/apidoc/utils.html#ddm.functions.solve_partial_conditions).
