### ISSUE TITLE
AttributeError: 'Solution' object has no attribute 'pdf'

### ISSUE THREAD

**Issue by alxgom** [mwshinn/PyDDM#81]
I'm trying to run the simple example

import matplotlib.pyplot as plt
from pyddm import Model
m = Model()
s = m.solve()
plt.plot(s.model.t_domain(), s.pdf("correct"))
plt.savefig("helloworld.png")
plt.show()

but i keep getting: 
AttributeError: 'Solution' object has no attribute 'pdf'

**Comment by mwshinn** [comment]
You are looking at the documentation for the latest github version (which has not been released on pip yet).  For documentation on the currently released version, see: https://pyddm.readthedocs.io/en/stable/quickstart.html or alternatively install the latest yet-unreleased version by downloading and compiling, as per the instructions in the readme.  The "pdf" function is new, you can use "pdf_corr()" instead.

**Comment by alxgom** [comment]
ahhh, thanks!
