### ISSUE TITLE
Could you give some reference papers about this package?

### ISSUE THREAD

**Issue by disadone** [mwshinn/PyDDM#9]
Hi! Max, Thanks for your DDM package.
Could you provide some related papers about this package? Thank you.

**Comment by mwshinn** [comment]
Papers will be available very soon, I will update this issue when they are online.

**Comment by mwshinn** [comment]
Here is one preprint which can be cited: https://www.biorxiv.org/content/10.1101/865501v1

There is another preprint on the way as well which describes PyDDM in more detail.

**Comment by disadone** [comment]
Thank you! Max. I really appreciate your work, though I don't have time reading through as a rotation student.

**Comment by mwshinn** [comment]
Here is the main preprint about PyDDM, which gives more details about its design, as well as a quantitative evaluation of its implementation: https://www.biorxiv.org/content/10.1101/2020.03.14.992065v1
