### ISSUE TITLE
Error with accuracy coding for biased starting point

### ISSUE THREAD

**Issue by mberns-ru** [mwshinn/PyDDM#90]
Hi! I'm having difficulty with implementing the biased starting point. I'm using the same code as provided in the docs:

```
import numpy as np
from pyddm import InitialCondition
class ICPointSideBias(InitialCondition):
    name = "A starting point with a left or right bias."
    required_parameters = ["x0"]
    required_conditions = ["left_is_correct"]
    def get_IC(self, x, dx, conditions):
        start = np.round(self.x0/dx)
        # Positive bias for left choices, negative for right choices
        if not conditions['left_is_correct']:
            start = -start
        shift_i = int(start + (len(x)-1)/2)
        assert shift_i >= 0 and shift_i < len(x), "Invalid initial conditions"
        pdf = np.zeros(len(x))
        pdf[shift_i] = 1. # Initial condition at x=self.x0.
        return pdf
```

But the assertion line for invalid initial conditions is inevitably called after a few iterations. Additionally, the docs explain that x0 can be positive or negative and that this indicates the side of the bias. However, the example code in the cookbook is written so that x0 is always positive:

```
model = Model(IC=ICPointSideBias(x0=Fittable(minval=0, maxval=1)),
              dx=.01, dt=.01)
```

I'm just a bit confused as how to how to approach this problem. The model works fine without the bias.

**Comment by mwshinn** [comment]
Can you ever get a situation where the boundary is greater than x0?  I.e., can the boundary ever be less than 1?

If not, please post more information including the full error output and the full code for the model and fitting.

**Comment by mberns-ru** [comment]
Yes, in our unbiased model, bound is often less than 1.

**Comment by mwshinn** [comment]
Your bound and x0 cannot intersect, otherwise the starting point will be outside the bounds.  Either adjust the bounds on one or both of the parameters to make sure they don't intersect, or use ICPointRatio instead: https://pyddm.readthedocs.io/en/stable/cookbook/initialconditions.html#ic-ratio

**Comment by mberns-ru** [comment]
Thank you!
