### ISSUE TITLE
How to visualize or output the value of the drift rate, boundary, and the value of 'x' during the simulation for a fitted model with given parameters. I want to visualize the process of how the information is accumulated and how the boundary is changed like the figure below: 

### ISSUE THREAD

**Issue by zhengli-hub** [mwshinn/PyDDM#98]
![2](https://github.com/mwshinn/PyDDM/assets/72850487/8b1d447b-5d12-41ee-b2f2-853a3d87a4b5)
![1](https://github.com/mwshinn/PyDDM/assets/72850487/b243f046-06df-4726-8ae2-b4b905543b2a)

**Comment by mwshinn** [comment]
Use the [simulate_trial](https://pyddm.readthedocs.io/en/latest/apidoc/model.html#pyddm.model.Model.simulate_trial) function.

Also, in the future, please ask questions like this in the Discussions section rather than reporting it as a bug.
